# frozen_string_literal: true

namespace :tailwindcss do
  desc "Write @source paths for bundled gems so dummy Tailwind can scan Flatpack"
  task :write_gem_sources do
    gems = {
      "flat_pack" => %w[app/components],
      "recording_studio" => %w[app/views app/components],
      "recording_studio_root_switchable" => %w[app/views app/components]
    }

    lines = ["/* Generated by rake tailwindcss:write_gem_sources — do not edit */", ""]
    gems.each do |name, dirs|
      spec = Bundler.load.specs.find { |loaded| loaded.name == name }
      next unless spec

      dirs.each do |dir|
        path = File.join(spec.full_gem_path, dir)
        next unless File.directory?(path)

        lines << %(@source "#{path}/**/*.{rb,erb}";)
      end
    end

    output = File.expand_path("../../app/assets/tailwind/gem_sources.css", __dir__)
    File.write(output, "#{lines.join("\n")}\n")
  end
end

task "tailwindcss:build" => "tailwindcss:write_gem_sources"
task "tailwindcss:watch" => "tailwindcss:write_gem_sources"
